version: "3.9"

services:
  mosquitto:
    image: eclipse-mosquitto:2
    ports:
     - "883:883"
    volumes:
    - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf
    - ./mosquitto/passwd.txt:/mosquitto/passwd.txt:ro
  mailhog:
    image: mailhog/mailhog:latest
    container_name: iot-smtp
    ports: 
      - "1025:1025"
      - "8025:8025"
  nodered:
    image: nodered/node-red:latest
    ports: 
     - "1880:1880"
    depends_on:
      - mosquitto
  
 
