# This is a Mosquitto configuration file that creates a listener on port 1883
# that allows unauthenticated access.

listener 883

allow_anonymous false
password_file /mosquitto/passwd.txt

listener 9883
protocol http_api
http_dir /usr/share/mosquitto/dashboard
